### ISSUE TITLE
Not working with ROM UNAPI's

### ISSUE THREAD

**Issue by ducasp** [Fubukimaru/MSXIRC#1]
The client won't work with UNAPI implementations in ROM. It works fine if UNAPI implementation is in RAM or Memory Mapped RAM segment.

**Comment by Fubukimaru** [comment]
Hello ducasp,

You had this working already, right?

**Comment by ducasp** [comment]
Yeah, pretty much on most of the issues, just finishing the code review
before sending it and opening issues as I see them during tests and code
review. I'm at 60% of the code now 🙂

Em sex, 21 de ago de 2020 07:01, Alberto Gutiérrez Torre <
notifications@github.com> escreveu:

**Comment by Fubukimaru** [comment]
Cool!

If I can be of any use, please tell me!

**Comment by ducasp** [comment]
By the way, following the documentation of what is being done, the cause of this issue was that Pasha changed the TCPCON routines to call UNAPI functions (MSXIRC used TCPCON as a foundation), as unlike TCPCON, segments being paged in or out are not depending on calling DOS functions or not, it is used everywhere across the program to switch "Windows". His re-write of that, making always allocate UNAPI segment on P1 and then re-allocating back whatever was on P1 worked fine for a memory mapper UNAPI or an UNAPI running on P3, but it was not in good shape for cartrige/rom on P2 UNAPI. Rewrote that part to have it working properly.

**Comment by ducasp** [comment]
Sorry for taking long to push the source code, I didn't finish all I've wanted and still want to finish what I've started, but I've updated the current version as it is in good shape for all issues it intend to fix. I think that the rest of improvments and code research will take at least a month or two before I finish as I've been really busy with my work, so thus I thought it is good to have 1.1 as it is right now and then make a 1.2. :)

**Comment by Fubukimaru** [comment]
Don't worry! And thanks for your huge work on this :D 

Is the user interface going to change much from 1.1 to 1.2? I was thinking about the documentation (#2). Also I could make a MSXHUB package for MSXIRC so that installing the software can be done directly from the MSX. What do you think?
