### ISSUE TITLE
Need documentation

### ISSUE THREAD

**Issue by ducasp** [Fubukimaru/MSXIRC#2]
There is no documentation about how to use the program, it is intuitive on some areas, and not on others, so a text manual would be great

**Comment by ducasp** [comment]
Help file is a text file, so I'm working on documenting everything on it. Then, probably can create a README.MD here with a few pictures to have an online document as well

**Comment by Fubukimaru** [comment]
When you upload the corrected version I can do that README :)

**Comment by ducasp** [comment]
Hi Fubu, I think the help file that is used by MSXIRC can be just copied as README.TXT and be used as a readme file template, might just need some work but that help is pretty much complete in detailing the usage of MSXIRC, keys, etc...

**Comment by Fubukimaru** [comment]
Done here:
https://github.com/Fubukimaru/MSXIRC/commit/0d97d2102e71f0290c6994b8587304155d3eb085
