### ISSUE TITLE
Can't connect to server when ini file is given as parameter

### ISSUE THREAD

**Issue by ducasp** [Fubukimaru/MSXIRC#5]
If you give a filename / ini filename as parameter for MSXIRC, even though the file is loaded ok and parameters are correctly read, when trying to connect MSXIRC is trying to resolve the filename instead of the server name...

**Comment by ducasp** [comment]
That was a legacy of the TCPCON code, it was checking if there was an input parameter when MSXIRC was called from MSX-DOS (i.e.: MSXIRC FILE.INI) and assuming that if there was a first input parameter, it was the server to connect to. This is just not proper for this IRC client as it is made to have only one parameter, the INI file that contains all parameters.

**Comment by Fubukimaru** [comment]
So now instead of being the server, you changed it to point to the file which was the right behaviour, right?
Thanks :)

**Comment by ducasp** [comment]
Kind of, just erased the part of code that looked for MSX-DOS Command Line
Arguments on the Connect function, as it was designed the Client needs a
proper INI file to load all server and nick related parameters, it doesn't
have default ones or a way to input those.

It might be a good idea for a future revision, though, to have a way to
manually set up those items in the Server Connection window :)

Em qua., 26 de ago. de 2020 às 08:17, Alberto Gutiérrez Torre <
notifications@github.com> escreveu:
