### ISSUE TITLE
MSXHUB package

### ISSUE THREAD

**Issue by Fubukimaru** [Fubukimaru/MSXIRC#7]
In order to offer installation using just the MSX (YEAH! WE DON'T WANT TO USE OUR PCs!) we can create a MSXHub package (https://msxhub.com/).

I propose the following steps:
- Create a github release
- Make a script to build the new MSXHub package in this repo
- Transfer that to MSXHUB repository for pull request

It would be nice that this process is as automated as possible, so that each new release gets published automatically.

**Comment by Fubukimaru** [comment]
@ducasp Should I use the com and files found here for the package? https://github.com/Fubukimaru/MSXIRC/tree/master/Ducasp_SJASM

**Comment by ducasp** [comment]
Hi Fubu,

Yeah, those are the files, I didn't want to mess with the original ones in your repositor MSXIRC project root, but if you find it suitable to move then, I have no objections, keeping them here or moving, your choice :)

A MSXHUB package is a great thing, I use it to distribute TELNET as well as HUBG :)

**Comment by Fubukimaru** [comment]
I have moved the files to the root. I'll start building the pkg.

**Comment by Fubukimaru** [comment]
I'm on it!
https://github.com/fr3nd/msxhub-packages/pull/42

**Comment by Fubukimaru** [comment]
https://github.com/fr3nd/msxhub-packages/pull/42

It will be available shortly. Closing this!

**Comment by Fubukimaru** [comment]
Also here: https://www.msx.org/downloads/msxirc-v11-irc-client-for-msx
