### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Fubukimaru** [Fubukimaru/MSXIRC#8]
This project doesn't have any license associated.

We should discuss it and ask @pterodl if he has any preference. What do you think @ducasp?

I would go for something like GPL 3.

**Comment by ducasp** [comment]
Hmmm not really sure about licensing, I think that the original author
should decide, my general take for projects that I choose to open the
source code is to allow any kind of work as long as it is not commercial
and source code is published as well, and any commercial usage should be
discussed with the owner of the original code which would be @pterodl

Not sure if GPL3 covers that, but that is my general choice 🙂

Em dom, 6 de dez de 2020 06:26, Alberto Gutiérrez Torre <
notifications@github.com> escreveu:

**Comment by Fubukimaru** [comment]
I got in touch with @pterodl and he told me the following:
```
About the license I want to say this:
1. I don't understand anything about licenses
2. I'm not going to license anything.
3. The code that I gave You please use freely at will.
4. if mentioning me as the author of the code causes difficulties, then you can not mention me.
5. you can consider yourself the author of the code :)
```

So I think that we can go for GPL3 and mention him as author as we're doing. What do you think :)?

**Comment by ducasp** [comment]
Up to you, you are the author, owner and everything else! lol! (No
objections to use GPL3)

Em qui., 10 de dez. de 2020 às 11:19, Alberto Gutiérrez Torre <
notifications@github.com> escreveu:

**Comment by Fubukimaru** [comment]
I'm only the guy who uploaded the code to github, you're the one that messed with the code here :P.

OK then! I'll put GPL3 as license
